# Generated by Django 3.0.2 on 2020-02-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('Age', models.IntegerField()),
                ('Height', models.IntegerField(verbose_name='Height-type in cm')),
                ('Weight', models.IntegerField(verbose_name='Weigh-type in kg')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('calc', models.FloatField(null=True)),
                ('slug', models.SlugField(editable=False, max_length=130, null=True)),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
    ]
